// generated by stringer -type OpType; DO NOT EDIT

package obscurate

import "fmt"

const _OpType_name = "OpXOROpAddOpSubOpSHLOpSHR"

var _OpType_index = [...]uint8{0, 5, 10, 15, 20, 25}

func (i OpType) String() string {
	if i >= OpType(len(_OpType_index)-1) {
		return fmt.Sprintf("OpType(%d)", i)
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
